### PR TITLE
Added bindHost parameter to config

### PR DESCRIPTION
**Pull request by isdn**
I have added bindHost to configs.
That might be useful in some cases, for example, when CommaFeed was deployed behind a proxy.

### CODE REVIEW

**Comment by Athou** [comment]
Why/in what case is limiting the IP address CommaFeed is listening on needed?

CommaFeed is running in production behind a proxy (nginx) without this setting and it works fine.

**Comment by isdn** [comment]
Hi.
As far as I understand, Dropwizard binds to all network interfaces by default (i.e. when no bindHost is provided).
Yes, it works fine, but this is a question of security/configuration. It should not be available on all interfaces when it is supposed to listen only on localhost.

**Comment by Athou** [comment]
Yes it indeed binds on 0.0.0.0 by default. Why not configure your firewall to only expose the ports you want to expose?

Also, since it's configurable, I guess you added that to your yml file. Why does it need to be in the repo?

**Comment by Athou** [comment]
I could entertain the idea of having bindHost set to 0.0.0.0 in the example file to document the fact that the setting exists though. I'm not sure it makes sense for the development file.

**Comment by isdn** [comment]
> Why not configure your firewall to only expose the ports you want to expose?

Well, yes, that is another way. But it is a good practice to bind local services to local network interfaces.

> I could entertain the idea of having bindHost set to 0.0.0.0 in the example file to document the fact that the setting exists though. I'm not sure it makes sense for the development file.

Both configs in the repo have publicUrl set to localhost.

**Pull request closed without merging**
