### PR TITLE
Add Alphabetical Sort

### PR DESCRIPTION
**Pull request by Hubcapp**
This pull request is premature, (feature not fully implemented to meet with standards of deployment to the thousands of users who use CommaFeed), but I want to get your opinion on whether or not you'd accept it into CommaFeed Main eventually.

This is a feature I've wanted for quite some time, and recently got the time to implement myself. See #670 for details on "Why"

Here's my commit comment:
" Add Alphabetical sorting

First "working" version of Alphabetical sorting in Commafeed. Needs better front end interface, translations, and probably the API is buggy surrounding "order" now b/c there is probably some code still that assumes there are only two possible ways to sort (date asc, date desc)."

### CODE REVIEW

**Comment by Hubcapp** [comment]
It's "pretty done" now probably. Front end looks fine, translations are placeheld. I'm using it now on my own instance, will be looking for any more bugs.

I haven't tested it in any feed with a non-latin-alphabet, so I don't know how it will act there. Also don't know how the API works, so I didn't test that either, but it could possibly work.

I guess you didn't get an alert that this pull request was created or something, so I'll try mentioning you @Athou

**Comment by Athou** [comment]
Hi, thanks for the PR!

I'm on holiday right now so I'll check your PR when I get back :)

**Comment by Hubcapp** [comment]
finding all kinds of fascinating information about sorting strings in non-latin alphabets.

Here's a paper about sorting in arabic. Looks pretty hard, but I think we can just use Locales for it.
http://www.wseas.us/e-library/conferences/2006elounda1/papers/537-391.pdf

Japanese (at least kanji, or any list that mixes the various "alphabets" of japanese) is a lost cause requiring human-like understanding of the context in which the word is said.
http://www.localizingjapan.com/blog/2011/02/13/sorting-in-japanese-%E2%80%94-an-unsolved-problem/
Apparently even Excel can't do it right which is good enough for me. It'll work in lists with just the simpler katakana or hiragana, as long as it's not mixed, in which case, the alphabet systems will be grouped.

In Chinese, it is standard to use something called "pinyin" to romanize them, so Java locale for Chinese is probably pretty happy. "It seems Locale.SIMPLIFIED_CHINESE ordered by Chinese Pinyin but Locale.TRADITIONAL_CHINESE ordered by stroke." according to one StackOverflow user. From what I read, Pinyin is typical, and "amount of pen strokes required to draw character" sorting is archaic but still used ceremonially (at the Bejing 2008 olympics countries marched out in stroke order)

Russian and Greek should "just work" like Latin since they use alphabetical order which lines up to character code order.

And in regards to sorting lists which have more than one type of alphabet in them (vomit) I found this comment which suggests you simply "don't" as it's not useful to anyone: http://stackoverflow.com/a/27337754/708928

As for somehow detecting what language the string is in and deciding locale based on that... I think that would be nice but pretty resource intensive (there's a 3rd party library I found for it), and it will be best to just set locale for sorting based on the language the user has set for the user interface... :)

**Comment by Hubcapp** [comment]
Wow merged? Okay. I expected a comment or something first but okay. As mentioned above, our non-latin friends may have some problems with this patch until the sort function is localized based on current language selected. Thanks for accepting the feature, I know you were skeptical about it 2 years or something ago. Honestly, even French (I think your native language?) with its latin alphabet supposedly benefits from localized sorting.

I haven't found any bugs, so that's good. Welcome back from vacation. :P

Oh, except that I found that I may want to scroll down to like "P" in the alphabetized list, but scrolling down too fast (purposely?) limits the user from loading more entries.

**Pull request merged**
